 export const AFRICAN_COUNTRIES = [
  { code: 'DZ', name: 'Algeria', dial: '+213' },
  { code: 'AO', name: 'Angola', dial: '+244' },
  { code: 'BJ', name: 'Benin', dial: '+229' },
  { code: 'BW', name: 'Botswana', dial: '+267' },
  { code: 'BF', name: 'Burkina Faso', dial: '+226' },
  { code: 'BI', name: 'Burundi', dial: '+257' },
  { code: 'CV', name: 'Cabo Verde', dial: '+238' },
  { code: 'CM', name: 'Cameroon', dial: '+237' },
  { code: 'CF', name: 'Central African Republic', dial: '+236' },
  { code: 'TD', name: 'Chad', dial: '+235' },
  { code: 'KM', name: 'Comoros', dial: '+269' },
  { code: 'CD', name: 'DR Congo', dial: '+243' },
  { code: 'CG', name: 'Republic of the Congo', dial: '+242' },
  { code: 'CI', name: 'Côte d\'Ivoire', dial: '+225' },
  { code: 'DJ', name: 'Djibouti', dial: '+253' },
  { code: 'EG', name: 'Egypt', dial: '+20' },
  { code: 'GQ', name: 'Equatorial Guinea', dial: '+240' },
  { code: 'ER', name: 'Eritrea', dial: '+291' },
  { code: 'SZ', name: 'Eswatini', dial: '+268' },
  { code: 'ET', name: 'Ethiopia', dial: '+251' },
  { code: 'GA', name: 'Gabon', dial: '+241' },
  { code: 'GM', name: 'Gambia', dial: '+220' },
  { code: 'GH', name: 'Ghana', dial: '+233' },
  { code: 'GN', name: 'Guinea', dial: '+224' },
  { code: 'GW', name: 'Guinea-Bissau', dial: '+245' },
  { code: 'KE', name: 'Kenya', dial: '+254' },
  { code: 'LS', name: 'Lesotho', dial: '+266' },
  { code: 'LR', name: 'Liberia', dial: '+231' },
  { code: 'LY', name: 'Libya', dial: '+218' },
  { code: 'MG', name: 'Madagascar', dial: '+261' },
  { code: 'MW', name: 'Malawi', dial: '+265' },
  { code: 'ML', name: 'Mali', dial: '+223' },
  { code: 'MR', name: 'Mauritania', dial: '+222' },
  { code: 'MU', name: 'Mauritius', dial: '+230' },
  { code: 'MA', name: 'Morocco', dial: '+212' },
  { code: 'MZ', name: 'Mozambique', dial: '+258' },
  { code: 'NA', name: 'Namibia', dial: '+264' },
  { code: 'NE', name: 'Niger', dial: '+227' },
  { code: 'NG', name: 'Nigeria', dial: '+234' },
  { code: 'RW', name: 'Rwanda', dial: '+250' },
  { code: 'ST', name: 'Sao Tome and Principe', dial: '+239' },
  { code: 'SN', name: 'Senegal', dial: '+221' },
  { code: 'SC', name: 'Seychelles', dial: '+248' },
  { code: 'SL', name: 'Sierra Leone', dial: '+232' },
  { code: 'SO', name: 'Somalia', dial: '+252' },
  { code: 'ZA', name: 'South Africa', dial: '+27' },
  { code: 'SS', name: 'South Sudan', dial: '+211' },
  { code: 'SD', name: 'Sudan', dial: '+249' },
  { code: 'TZ', name: 'Tanzania', dial: '+255' },
  { code: 'TG', name: 'Togo', dial: '+228' },
  { code: 'TN', name: 'Tunisia', dial: '+216' },
  { code: 'UG', name: 'Uganda', dial: '+256' },
  { code: 'ZM', name: 'Zambia', dial: '+260' },
  { code: 'ZW', name: 'Zimbabwe', dial: '+263' },
];