import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import Providers from "./providers"; // Import the new client component
import "../globals.css"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  // 1. Await params (Next.js 15+ requirement)
  const { locale } = await params;

  // 2. verify locale exists in your routing config
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // 3. Get messages for this specific language
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* NextIntlClientProvider takes a plain object (messages), so it is fine here */}
        <NextIntlClientProvider messages={messages}>
          {/* The QueryClient and Auth logic is now safely inside this Client Component */}
          <Providers>
            {children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}